version: '3.2'
services:
  bot:
    build: .
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  mysql:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: announcement
      MYSQL_ROOT_PASSWORD: Password1!
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
