version: '3.2'
services:
  bot:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - '3000:3000'
    command: npm run start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
  mysql:
    image: mysql:latest
    command: --max_allowed_packet=32505856 # Set max_allowed_packet to 256M (or any other value)
    ports:
      - '3333:3306'
    environment:
      MYSQL_DATABASE: announcement
      MYSQL_ROOT_PASSWORD: Password1!
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
